### ISSUE TITLE
base IRI

### ISSUE THREAD

**Issue by eibar-flores** [emmo-repo/domain-battery#24]
Currently the base IRI for domain-battery uses the github.io URL. Is the intention to use the emmo.info IRIs like the one in domain-electrochemistry? (http://emmo.info/electrochemistry#)

**Comment by jesper-friis** [comment]
It is simply a decision to take, but I think that it make sense to use http://emmo.info/battery# as base IRI. Aren't you already using domain-battery? How much work will it be to update everything using it?

When changing IRIs of units in EMMO from uuid's to human readable names, we kept the old IRIs in a special module called deprecated and added owl:deprecated and dcterms:isReplacedBy relations. Maybe you could do the same? This way you give users of the ontology some time to adapt to the changes...

**Comment by jsimonclark** [comment]
for the move to the w3id.org namespace we will use https://w3id.org/emmo/domain/battery#
